{{ $ocpVersionXY := printf "%d.%d" .OCPVersion.Major .OCPVersion.Minor }}
{{ $ocpVersionXYZ := .OCPVersion }}
{{ $odfVersionXY := printf "%d.%d" .ODFVersion.Major .ODFVersion.Minor }}

apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: {{ .DestinationRegistry }}/ztpfw/oc-mirror
mirror:
  platform:
    channels:
    - name: candidate-{{ $ocpVersionXY }}
      minVersion: {{ $ocpVersionXYZ }}
    - name: stable-{{ $ocpVersionXY }}
      minVersion: {{ $ocpVersionXYZ }}
  operators: # Operators we want to mirror
  - catalog: {{ .RedhatOperatorsIndex }}:v{{ $ocpVersionXY }}
    packages:
    - name: quay-operator
      channels:
      - name: stable-3.7
      - name: stable-3.8
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: metallb-operator
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: odf-operator
      channels:
      - name: stable-{{ $odfVersionXY }}
    - name: lvms-operator
      channels:
      - name: stable-{{ $odfVersionXY }}
        #- name: nfd
        #  channels:
        #  - name: stable
        #- catalog: {{ .CertifiedOperatorsIndex }}:v{{ $ocpVersionXY }}
        #  packages:
        #  - name: gpu-operator-certified
        #    #channels:
        #    #- name: stable
  additionalImages:
  - name: quay.io/ztpfw/ui:latest