apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentclusterinstalls.extensions.hive.openshift.io
spec:
  group: extensions.hive.openshift.io
  names:
    kind: AgentClusterInstall
    listKind: AgentClusterInstallList
    plural: agentclusterinstalls
    singular: agentclusterinstall
    shortNames:
    - aci
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true