apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: infraenvs.agent-install.openshift.io
spec:
  group: agent-install.openshift.io
  names:
    kind: InfraEnv
    listKind: InfraEnvList
    plural: infraenvs
    singular: infraenv
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true