apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nmstateconfigs.agent-install.openshift.io
spec:
  group: agent-install.openshift.io
  names:
    kind: NMStateConfig
    listKind: NMStateConfigList
    plural: nmstateconfigs
    singular: nmstateconfig
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true